version: "3.9"

services:
  adminer:
    build: .
    container_name: adminer
    restart: on-failure
    ports:
      - 9080:8080
    networks:
      - database

networks:
  database:
    name: database
    driver: bridge
