version: "3.5"

services:
  adminer:
    build: .
    container_name: adminer
    restart: always
    ports:
      - 9080:8080
    networks:
      - database

networks:
  database:
    external: true
